[build]
  publish = "cupper-hugo-theme/public"
  command = "cd cupper-hugo-theme/src && hugo --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.83.1"
  HUGO_THEME = "cupper-hugo-theme"
  HUGO_BASEURL = "https://cupper-hugo-theme.netlify.app"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
