[build]
  publish = "src"
  command = "cd cupper-hugo-theme/src && hugo --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.83.1"
  HUGO_THEME = "cupper-hugo-theme"
  HUGO_BASEURL = "https://cupper-hugo-theme.netlify.app"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"

[context.production.environment]
HUGO_VERSION = "0.104.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"